# This file was generated by GoReleaser. DO NOT EDIT.
cask "qmdverify" do
  name "qmdverify"
  desc "QMD file compatibility checker for reMarkable devices"
  homepage "https://github.com/rmitchellscott/rm-qmd-verify-cli"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qmdverify"

  on_macos do
    on_intel do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_macOS_x86_64.tar.gz"
      sha256 "6362fd70b22bf0e23d5fbed6102e5e3ebfa79e99585705beb4615a792b48da0b"
    end
    on_arm do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_macOS_aarch64.tar.gz"
      sha256 "762a147084f9316ff4908f5ff16251c48d767f9a9dfec18eb3e00730dcebbc01"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_linux_x86_64.tar.gz"
      sha256 "b98d4c01d0d03a0373904925a590bbe4e1d4d2a7399610044b2c545e7248b809"
    end
    on_arm do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_linux_aarch64.tar.gz"
      sha256 "ad16c39ce7adeaf7269a17b8ba9c77757559eb97fcd856ca3d14f022500ffa3e"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qmdverify"]
    end
  end

  # No zap stanza required
end
