# This file was generated by GoReleaser. DO NOT EDIT.
cask "qmdverify" do
  name "qmdverify"
  desc "QMD file compatibility checker for reMarkable devices"
  homepage "https://github.com/rmitchellscott/rm-qmd-verify-cli"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qmdverify"

  on_macos do
    on_intel do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_macOS_x86_64.tar.gz"
      sha256 "a0681bf64709ae9bebb2b6d6f16dfb47863c05a4dcc087f8eee9afc963fb10d9"
    end
    on_arm do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_macOS_aarch64.tar.gz"
      sha256 "84e491581d3054ce2590da2c3afbee7abfa59b2ae540b5c82d4aa54dfbb00147"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_linux_x86_64.tar.gz"
      sha256 "fd5617ba42b38cf0a0fb486a81c2e50ca7f195b53b848aae8cd48c78cfdd384f"
    end
    on_arm do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_linux_aarch64.tar.gz"
      sha256 "62140add4c181adc0170126ef3a23155095385826a0f0578e237425e4e078ed2"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qmdverify"]
    end
  end

  # No zap stanza required
end
