# This file was generated by GoReleaser. DO NOT EDIT.
cask "qmdverify" do
  name "qmdverify"
  desc "QMD file compatibility checker for reMarkable devices"
  homepage "https://github.com/rmitchellscott/rm-qmd-verify-cli"
  version "1.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "qmdverify"

  on_macos do
    on_intel do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_macOS_x86_64.tar.gz"
      sha256 "18329b4e40a21b7ae3ec8b3e7c1698589d1d3a179e127482a1a74932e3a2d19e"
    end
    on_arm do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_macOS_aarch64.tar.gz"
      sha256 "d8ab568755520fc54982caf51889536358b5a64d14dd68683cbaf5b6f3388e7d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_linux_x86_64.tar.gz"
      sha256 "d61033d5d52703f4eea596522fb0a62bfca2a3d056620424298c0d726ef8bfeb"
    end
    on_arm do
      url "https://github.com/rmitchellscott/rm-qmd-verify-cli/releases/download/v#{version}/rm-qmd-verify-cli_#{version}_linux_aarch64.tar.gz"
      sha256 "55dfe1aa4242032c2b4adeff807ce7c347791b0a132621ace537cac86981494d"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/qmdverify"]
    end
  end

  # No zap stanza required
end
