# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wxcraft < Formula
  desc "METAR and TAF retrieval and decoding"
  homepage "https://github.com/rmitchellscott/WxCraft"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rmitchellscott/WxCraft/releases/download/v0.0.5/wxcraft_Darwin_x86_64.tar.gz"
      sha256 "01b1728f9b0aba31a6fc297f3fe842aafd6f4969762bbab5035e7159d191a69d"

      def install
        bin.install "wxcraft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rmitchellscott/WxCraft/releases/download/v0.0.5/wxcraft_Darwin_arm64.tar.gz"
      sha256 "7dd085b9c84c4e7607597f7c45b4c5fa0fa99718179647ae1ba0a1ca41247a0a"

      def install
        bin.install "wxcraft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rmitchellscott/WxCraft/releases/download/v0.0.5/wxcraft_Linux_x86_64.tar.gz"
      sha256 "dc620ca35dc9470a36326ef0d87dcfc9c3ed4acf9d548ccf1233c73965167ada"
      def install
        bin.install "wxcraft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rmitchellscott/WxCraft/releases/download/v0.0.5/wxcraft_Linux_arm64.tar.gz"
      sha256 "16e8878d0286ddb2fdcdd58995c8924c5798ee3153c9c9ddd3a0fc85ad2a36eb"
      def install
        bin.install "wxcraft"
      end
    end
  end
end
