# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wxcraft < Formula
  desc "METAR and TAF retrieval and decoding"
  homepage "https://github.com/rmitchellscott/WxCraft"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rmitchellscott/WxCraft/releases/download/v0.0.1/wxcraft_Darwin_x86_64.tar.gz"
      sha256 "4fe1c5fe789aafa8c5a55fb744b7053e92b382a62c6f947e0fe3b2fc98430d36"

      def install
        bin.install "wxcraft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rmitchellscott/WxCraft/releases/download/v0.0.1/wxcraft_Darwin_arm64.tar.gz"
      sha256 "761a6510b99c46d33d48839336d303928545647092c8c6e53d50d818a976c9e7"

      def install
        bin.install "wxcraft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rmitchellscott/WxCraft/releases/download/v0.0.1/wxcraft_Linux_x86_64.tar.gz"
        sha256 "aaf0477e094b06f960f48e5a9263af9695e4174bec325acd3119fad2dbfa94d3"

        def install
          bin.install "wxcraft"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rmitchellscott/WxCraft/releases/download/v0.0.1/wxcraft_Linux_arm64.tar.gz"
        sha256 "77859288ccca10bcb4a62643088c4d02dc0dd5dfafc0703d90326b13029ca3d3"

        def install
          bin.install "wxcraft"
        end
      end
    end
  end
end
